name = "MTKHelpers"
uuid = "2725b469-bb7f-4d1a-ba58-ced332a70bc7"
authors = ["Thomas Wutzler <twutz@bgc-jena.mpg.de> and contributors"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test"]
